final-LoVisto/ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import include,path
from django.contrib.auth.views import LoginView as login
from django.contrib.auth.views import LogoutView as logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lovisto/', include('lovisto.urls')),
    path('login/', login.as_view()),
    path('logout/', logout.as_view())
]

final-LoVisto/ProyectoFinal/lovisto/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.indexpage,name='indexpage'),
    path('user/<str:llave>', views.user_page,name='user_page'),
    path('resumenaportaciones', views.contributions_page,name='contributions_page'),
    path('informacion', views.page_info,name='page_info'),
    path('<str:llave>',views.page_resource,name='page_resource'),
]

final-LoVisto/ProyectoFinal/lovisto/models.py
from django.db import models

# Create your models here.
class Contenido(models.Model):
    title = models.CharField(max_length=64) #Titulo de la noticia
    url = models.TextField() #La URL
    user = models.TextField()
    date = models.DateTimeField('published')
    Comments = models.IntegerField() #Numero de comentarios
    votes_pos = models.IntegerField()
    votes_neg = models.IntegerField()

    def __str__(self):
        return self.clave + ":" + self.valor

class Comentario(models.Model):
    content = models.ForeignKey(Contenido,on_delete=models.CASCADE) #Cada comentario va al contenido
    info = models.TextField() #Comentario a poner
    imagen = models.TextField(default="No_url")
    title = models.CharField(max_length=64)
    date = models.DateTimeField('published')
    user = models.TextField()

    def __str__(self):
        return self.title + ":" + self.valor

class Voto(models.Model):
    content = models.ForeignKey(Contenido,on_delete=models.CASCADE)#Un voto va para el contenido
    user = models.TextField() #usuario que ha votado
    valor = models.TextField() #Positivo o negativo

    def __str__(self):
        return str(self.content) + ":" + self.user

final-LoVisto/ProyectoFinal/lovisto/views.py
from .models import Contenido, Comentario, Voto
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import redirect,render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from bs4 import BeautifulSoup
import requests
from django.http import JsonResponse

import requests
# Create your views here.

def logout_view(request):
    logout(request)

def get_last_from_list_5(n, lista):
    lista = lista.objects.all()
    return lista.order_by('-id')[:n]

@csrf_exempt
def indexpage(request):

    modo = 0 #Por defecto claro
    if request.method == "POST":
        action = request.POST['action']
        if action == "Iniciar sesion":
            return redirect('/login')
        elif action == "Cerrar sesion":
            logout_view(request)
            return redirect('/lovisto')
        elif action == "añadir contenido":
                title = request.POST['title']
                url = request.POST['url']
                try:
                    c = Contenido.objects.get(title=title)
                    c.delete()
                except Contenido.DoesNotExist:
                    c = Contenido(title=title,
                                url=url,
                                user=request.user.username,
                                date=timezone.now(),
                                Comments=0,
                                votes_pos=0,
                                votes_neg=0)
                    c.save()
        elif action == "Pagina Usuario":
            return redirect('/lovisto/user/' + request.user.username)
        elif action == "Aportaciones totales":
            return redirect('/lovisto/resumenaportaciones')
        elif action == "Informacion":
            return redirect('/lovisto/informacion')
        elif action == "Modo oscuro":
            modo= 1
        elif action == "Modo claro":
            modo = 0

    content_list = Contenido.objects.all()
    content_list = list(reversed(content_list))
    content_list_apor = content_list[0:10]
    last3_apor = get_last_from_list_5(3,Contenido)
    aportaciones = get_last_from_list_5(5, Contenido)
    context = {
        'content_list_apor': content_list_apor,
        'content_list': content_list,
        'numeroapor': aportaciones,
        'last3_apor':last3_apor,
        'modo':modo
    }
    return render(request, 'lovisto/PaginaPrincipal.html', context)

def user_page(request,llave):
    modo = 0#Por defecto claro
    if request.method =="POST":
        action=request.POST['action']
        if request.POST['action'] == "Pagina principal":
            return redirect('/lovisto')
        elif action== "Cerrar sesion":
            logout_view(request)
            return redirect('/lovisto')
        elif action== "Aportaciones totales":
            return redirect('/lovisto/resumenaportaciones')
        elif action == "Informacion":
            return redirect('/lovisto/informacion')
        elif action == "Modo oscuro":
            modo = 1
        elif action == "Modo claro":
            modo = 0
    content_list = Contenido.objects.all()
    coment_list = Comentario.objects.all()
    vote_list = Voto.objects.all()
    last3_apor = get_last_from_list_5(3, Contenido)
    context = {
         'content_list': content_list,
         'coment_list': coment_list,
         'vote_list':vote_list,
         'last3_apor':last3_apor,
         'modo':modo
     }
    return render(request,'lovisto/PaginaUsuario.html',context)

def contributions_page(request):
    modo=0#Por defecto claro
    if request.method == "POST":
        action = request.POST['action']
        if request.POST['action'] == "Pagina principal":
            return redirect('/lovisto')
        elif action == "Cerrar sesion":
            logout_view(request)
            return redirect('/lovisto')
        elif action == "Pagina Usuario":
            return redirect('/lovisto/user/' + request.user.username)
        elif action== "Informacion":
            return redirect('/lovisto/informacion')
        elif action == "Modo oscuro":
            modo = 1
        elif action == "Modo claro":
            modo = 0

    content_list = list(reversed(Contenido.objects.all()))
    coment_list = Comentario.objects.all()
    vote_list = Voto.objects.all()
    last3_apor = get_last_from_list_5(3, Contenido)
    context = {
        'content_list': content_list,
        'coment_list': coment_list,
        'vote_list': vote_list,
        'last3_apor':last3_apor,
        'modo':modo
    }
    return render(request, 'lovisto/aportaciones.html', context)

def page_info(request):
    modo=0#Por defecto claro
    if request.method =="POST":
        action=request.POST['action']
        if request.POST['action'] == "Pagina principal":
            return redirect('/lovisto')
        elif action == "Cerrar sesion":
            logout_view(request)
            return redirect('/lovisto')
        elif action == "Pagina Usuario":
            return redirect('/lovisto/user/' + request.user.username)
        elif action == "Informacion":
            return redirect('/lovisto/informacion')
        elif action == "Aportaciones totales":
            return redirect('/lovisto/resumenaportaciones')
        elif action == "Modo oscuro":
            modo = 1
        elif action == "Modo claro":
            modo = 0

    last3_apor = get_last_from_list_5(3, Contenido)
    context = {
        'last3_apor': last3_apor,
        'modo':modo
    }
    return render(request,'lovisto/Paginainformacion.html',context)

@csrf_exempt
def page_resource(request,llave):
    modo=0 #Por defecto claro
    if request.method == "PUT":
        valor = request.body.decode('utf-8')
    if request.method == "POST":
        if request.POST['action'] == "Iniciar sesion":
            return redirect('/login')

        elif request.POST['action'] == "Cerrar sesion":
            logout_view(request)
            return redirect('/lovisto')

        elif request.POST['action'] == "Pagina principal":
            return redirect('/lovisto')

        elif request.POST['action'] == "Pagina Usuario":
            return redirect('/lovisto/user/<request.user.username>')

        elif request.POST['action'] == "Aportaciones totales":
            return redirect('/lovisto/resumenaportaciones')

        elif request.POST['action'] == "Informacion":
            return redirect('/lovisto/informacion')

        elif request.POST['action'] == "Enviar comentario":
            contenido = Contenido.objects.get(title=llave)
            contenido.Comments = contenido.Comments + 1
            c = Comentario(content=contenido,info=request.POST['info'],
                            imagen=request.POST['url'],
                            title = request.POST['titulo'],
                            date=timezone.now(),
                            user=request.user.username)
            c.save()
            contenido.save()

        elif request.POST['action'] == "LIKE":
            contenido = Contenido.objects.get(title=llave)
            contenido.votes_pos = contenido.votes_pos + 1
            contenido.save()
            voto = Voto(content=Contenido.objects.get(title=llave),
                        user=request.user.username,
                        valor="like")
            voto.save()

        elif request.POST['action'] == "DISLIKE":
            contenido = Contenido.objects.get(title=llave)
            contenido.votes_neg = contenido.votes_neg + 1
            contenido.save()
            voto = Voto(content=Contenido.objects.get(title=llave),
                       user=request.user.username,
                       valor="dislike")
            voto.save()

        elif request.POST['action'] == "Borrar voto":
            contenido = Contenido.objects.get(title=llave)
            votedelete = Voto.objects.get(content=Contenido.objects.get(title=llave),
                                       user=request.user.username)
            if votedelete.valor == "like":
                contenido.votes_pos = contenido.votes_pos - 1
            elif votedelete.valor == "dislike":
                contenido.votes_neg = contenido.votes_neg - 1
            contenido.save()
            votedelete.delete()

        elif request.POST['action'] == "Borrar comentario":
            contenido = Contenido.objects.get(title=llave)
            try:
                comentariodelete = Comentario.objects.get(content=Contenido.objects.get(title=llave),
                                                      title=request.POST['comentario'],
                                                      user=request.user.username)
                contenido.Comments = contenido.Comments - 1
                contenido.save()
                comentariodelete.delete()
            except Comentario.DoesNotExist:
                content = Contenido.objects.get(title=llave)
                context = {"content": content}
                return render(request, 'lovisto/comentarionoencontrado.html', context)

        elif request.POST['action'] == "Modificar url":
            try:
                c= Contenido.objects.get(title=llave)
                c.url=request.POST['valor']
                c.save()
            except Contenido.DoesNotExist:
                c=Contenido(title=llave, url=request.POST['valor'])
                c.save()

        elif request.POST['action'] == "Modificar titulo":
            contenido = Contenido.objects.get(title=llave)
            if contenido:
                contenido.title = request.POST['titulo']
                contenido.save()
                return redirect('/lovisto/'+ request.POST['titulo'])

        elif request.POST['action'] == "Borrar aportacion":
            try:
                c = Contenido.objects.get(title=llave)
                c.delete()
                return redirect('/lovisto')
            except Contenido.DoesNotExist:
                c = Contenido.objects.get(title=llave, url=valor)

final-LoVisto/ProyectoFinal/templates/lovisto/Otrosrecursosnoreconocidos.html
{% extends 'lovisto/PaginaContenido.html' %}
{%block aportacion%}
<div class="og">
  <p>Recurso no reconocido en nuestra plataforma, Informacion extraida:</p>
  <p>Este es el titulo:{{title}}</p>
  <img src={{img}}>
  </div>
    <a href={{content.url}}>Artículo original</a>.</p>
  </div>
</div>
{%endblock%}

final-LoVisto/ProyectoFinal/templates/lovisto/PaginaContenido.html
{% extends 'lovisto/schema.html' %}
{%block cuerpo%}
    <tr>
       <td>
            <table style="width:auto" align="center">
                <th><a href="{{content.url}}">{{content.url}}</a></th>
                <tr>
                    <td><strong>Título :</strong></td>
                    <td>{{ content.title }}</td>
                </tr>
                <tr>
                    <td><strong>Votos positivos :</strong></td>
                    <td>{{ content.votes_pos }}</td>
                </tr>
                <tr>
                    <td><strong>Votos negativos :</strong></td>
                    <td>{{ content.votes_neg }}</td>
                </tr>
                <tr>
                    <td><strong>Fecha de publicación :</strong></td>
                     <td>{{ content.date }}</td>
                </tr>
                <tr>
                    <td><strong>Numero de comentarios :</strong></td>
                    <td>{{ content.Comments }}</td>
                </tr>
             </table>
       </td>
    </tr>

     {%if request.user.is_authenticated%}
        {%if content.voto_set.all%}
            {% for voto in content.voto_set.all%}
                     {%ifequal voto.user request.user.username %}
                        <br><strong>Usted {{ request.user.username}} ya ha votado [{{voto.valor}}]</strong>
                        <form action="" method ="POST">
                            {% csrf_token %}
                         <td><input class="boton_personalizado" type="submit" name="action" value="Borrar voto"></td>
                        </form>
                        <br>
                    {%else%}
                    <br><br>
                        <table style="width:auto" align="center">
                        <form action="" method ="POST">
                        {% csrf_token %}
                            <button class ="save btn-like" name = 'action' value = "LIKE">
                            <img src="https://i.pinimg.com/originals/aa/25/f7/aa25f7b35745c79643a6b427f6130807.png" width = "80" height = "50">
                            </button>
                        </form>
                        <form action="" method ="POST">
                        {% csrf_token %}
                            <button class ="save btn-like" name = 'action' value = "DISLIKE">
                            <img src="https://i.pinimg.com/originals/1b/1b/ee/1b1beea936af4917e2a1ea927905b03f.png" width = "70" height = "50">
                            </button>
                        </form>
                        </table>
                        <br><br><br>
                    {%endifequal%}
             {%endfor%}
        {%else%}
        <br>
        <table style="width:auto" align="center">
            <form action="" method ="POST">
                    {% csrf_token %}
                <button class ="save btn-like" name = 'action' value = "LIKE">
                 <img src="https://i.pinimg.com/originals/aa/25/f7/aa25f7b35745c79643a6b427f6130807.png" width = "80" height = "50">
                </button>
            </form>
            <form action="" method ="POST">
                    {% csrf_token %}
                 <button class ="save btn-like" name = 'action' value = "DISLIKE">
                 <img src="https://i.pinimg.com/originals/1b/1b/ee/1b1beea936af4917e2a1ea927905b03f.png" width = "60" height = "50">
                </button>
            </form>
            </table>

            <br><br>
        {%endif%}
    {%endif%}
{%block aportacion%}
{%endblock%}
<br><br>
    <p><strong>Comentarios</strong></p>
    {%if content.comentario_set.all%}
        {% for comentario in content.comentario_set.all%}
            <table style="width:auto" align="center">
                    <tr>
                           <td><b><strong>Titulo:</strong><b/></td>
                           <td>{{comentario.title }}</td>
                    </tr>
                    <tr>
                        <td><b><strong>Descripción:</strong><b/></td>
                           <td> {{comentario.info }}</td>
                    </tr>
                     <tr>
                        <td><b><strong>Usuario:</strong><b/></td>
                           <td> {{comentario.user }}</td>
                    </tr>
                    <tr>
                        <td><b><strong>Fecha:</strong><b/></td>
                        <td>{{ comentario.date }}</td>
                    </tr>
                    {%if comentario.imagen%}
                    <tr>
                        <td><b>Imagen</b></td>
                        <td><img src = {{comentario.imagen}} align="center" width="150"></td>
                    </tr>
                    {%endif%}
            </table>
            <br>
        {%endfor%}
    {%else%}
        <p>No hay comentarios</p>
    {%endif%}
    <br><br>
    <p><strong>Votos</strong></p>
    {%if content.voto_set.all%}
        {% for voto in content.voto_set.all%}
            <table style="width:auto" align="center">
                        <tr>
                            <td><b><strong>Usuario:</strong><b/></td>
                            <td>{{voto.user }}</td>
                        </tr>
                        <tr>
                            <td><b><strong>Voto:</strong><b/></td>
                            <td> {{voto.valor }}</td>
                        </tr>
            </table>
        {%endfor%}
    {%else%}
        <p>No hay votaciones</p>
    {%endif%}
    <br>
{%endblock%}
{%block lateral%}
{%if request.user.is_authenticated%}
<p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo oscuro">
        </form>
    <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo claro">
        </form>
    <br>
<p><strong>Introduce un nuevo comentario:</strong></p>
            <form action="" method ="POST">
                <table style="width:auto" align="left">
                    {% csrf_token %}
                       <tr>
                           <td>Titulo:</td>
                           <td> <input type="text" name="titulo"></td>
                        </tr>
                        <tr>
                           <td> Descripcion:</td>
                           <td> <input type="text" name="info"></td>
                        </tr>
                        <tr>
                           <td>URL imagen:</td>
                           <td> <input type="text" name="url"></td>
                        </tr>
            </table> <br> <br> <br><br>
                    <br/><input class="boton_personalizado"  type="submit" name="action" value="Enviar comentario">
                </form>
{% else%}
    <br>
    <p>Para poder comentar en una publicacion y editarla tiene que haber iniciado sesion</p>
{%endif%}
<br>
    {%ifequal  request.user.username  content.user  %}
    <p><strong>Modificar titulo:</strong></p>
        <form action="" method ="POST">
            <table style="width:auto" align="left">
                    {% csrf_token %}
                <tr>
                   <td> Cambiar titulo: </td>
                    <td><input type="text" name="titulo"></td>
                </tr>
            </table>
            <br> <br>
            <input class="boton_personalizado" type="submit" name="action" value="Modificar titulo">
        <br>
        <br>
        <p><strong>Modificar url:</strong></p>
        <form action="" method ="POST">
            <table style="width:auto" align="left">
                    {% csrf_token %}
                <tr>
                   <td> Nueva url: </td>
                    <td><input type="text" name="valor"></td>
                </tr>
            </table>
            <br> <br>
            <input class="boton_personalizado" type="submit" name="action" value="Modificar url">
        </form>
        <br>
        <p><strong>Borrar comentario:</strong></p>
        <form action="" method ="POST">
            <table style="width:auto" align="left">
                    {% csrf_token %}
                <tr>
                   <td>Título comentario</td>
                    <td><input type="text" name="comentario"></td>
                </tr>
            </table>
            <br> <br>
            <input class="boton_personalizado" type="submit" name="action" value="Borrar comentario">
        </form>
        <br>
        <p><strong>Cambiar contenido comentario:</strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Cambiar comentario">
        </form>
        <br>
        <p><strong>Borrar aportacion:</strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Borrar aportacion">
        </form>
    <br>
    <p>Previsualizacion de <a href="{{content.url}}">{{content.title}}</a></p>
            <iframe src="{{content.url}}" height="400" width="65%" name="demo">
             <p>Su navegador no es compatible con iframes</p>
            </iframe>

    {%endifequal%}
<br>
{%endblock%}

final-LoVisto/ProyectoFinal/templates/lovisto/PaginaPrincipal.html
{% extends 'lovisto/schema.html' %}
{%block cuerpo%}
    {%if content_list_apor%}
<h1>
    <strong>Contenidos añadidos</strong>
</h1>
        {%for content in content_list_apor%}
<br>
                    <!-- Hay que meter la URL correcta Ej:https://www.eltiempo.es/-->
                      <table style="width:auto" align="center">
                        <th><a href="{{content.url}}">{{content.url}}</a></th>
                        <tr>
                            <td>Titulo:</td>
                            <td>{{ content.title }}</td>
                        </tr>
                        <tr>
                           <td>Votos positivos : </td>
                            <td>{{ content.votes_pos}}</td>
                        </tr>
                        <tr>
                            <td>Votos negativos : </td>
                            <td>{{ content.votes_neg }}</td>
                        </tr>
                        <tr>
                            <td>Fecha de publicación : </td>
                             <td>{{ content.date }}</td>
                        </tr>
                          <tr>
                            <td>Publicado por el usuario: </td>
                             <td>{{ content.user }}</td>
                        </tr>
                        <tr>
                            <td>Número de comentarios : </td>
                            <td>{{ content.Comments }}</td>
                        </tr>
                        <form action="http://localhost:8000/lovisto/{{content.title}}" method ="POST">
                                {% csrf_token %}
                             <td><input class="boton_contenido" type="submit" name="action" value="Pagina aportacion"></td>
                           </tr>
                        </form>
                     </table>
               </td>
            </tr>
        {%endfor%}
    {%else%}
        <p><strong>No hay contenidos que mostrar</strong></p>
    {%endif%}
{% endblock %}
{%block lateral%}
    <table style="width:auto" align="left">
        <tr>
            <td><a href="/lovisto/index?format=xml/" class="nav-link px-2 text-dark">XML</a></td>
            <td><a href="/lovisto/index?format=json/" class="nav-link px-2 text-dark">JSON</a></td>
        </tr>
    </table>
    <br><br>
    {%  if request.user.is_authenticated%}
    <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo oscuro">
        </form>
    <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo claro">
        </form>
    <br>
    <p><strong>Introduce un nuevo contenido:</strong><p>
        <form action="" method ="POST">
             {% csrf_token %}
            <table style="width:auto" align="left">
               <tr>
                   <td>Titulo:</td>
                   <td><input type="text" name="title"></td>
               </tr>
                <tr>
                     <td>URL:</td>
                     <td><input type="text" name="url"></td>
                </tr>
            </table>
    <input class="boton_contenido" type="submit" name="action" value="añadir contenido">
        </form>
  {% else %}
    <br>
    <p><strong>Para poder introducir un contenido necesitas estar registrado</strong></p>
    {%endif%}
{% if request.user.is_authenticated%}
        {%if numeroapor%}
<br><br>
<!-- Ultimas 5 aportaciones-->
    <strong>Últimas cinco aportaciones:</strong>
             {%for content in numeroapor%}
<br>
                 {% ifequal content.user request.user.username %}
                        <a href="{{content.url}}">{{content.title}}</a>
                 {%endifequal%}
            {%endfor%}
             <br>
    {%endif%}
{%endif%}
{% endblock %}

final-LoVisto/ProyectoFinal/templates/lovisto/Paginainformacion.html
{% extends 'lovisto/schema.html' %}
{%block cuerpo%}
<strong>
<p>
  En esta página se encuentra la informacion de la práctica,<br>
<p/>
<p>
    Soy Daniel Álvarez Bustos,del grado de Tecnologías de la Informacion <br>
    y he usado la herramienta Django, utilizando Python para crear el proyecto. <br>
  <br>Implementado en un sistema Ubuntu 20.04.2 LTS
<p/>
<ul>
  <li>Para el css la información la he sacado de páginas como:</li>
</ul>
<ol>
    <li><a href="https://mosaic.uoc.edu/ac/le/es/m6/ud7/index.html">https://mosaic.uoc.edu/ac/le/es/m6/ud7/index.html</a></li>
    <li><a href="https://www.w3.org/Style/Examples/011/firstcss.es.html">https://www.w3.org/Style/Examples/011/firstcss.es.html</a></li>
    <li><a href="https://uniwebsidad.com/libros/xhtml/capitulo-5/listas-ordenadas">https://uniwebsidad.com/libros/xhtml/capitulo-5/listas-ordenadas</a></li>
    <li><a href="https://ichi.pro/es/cree-un-boton-me-gusta-personalizado-con-html-css-y-javascript-vanilla-202446046497453">https://ichi.pro/es/cree-un-boton-me-gusta-personalizado-con-html-css-y-javascript-vanilla-202446046497453</a></li>
<ol/>
    <br>
    <ul>
       <li>Para las plantillas la información la he sacado de páginas como:</li>
    </ul>
    <ol>
        <li><a href="https://docs.djangoproject.com/en/3.2/topics/templates/">https://docs.djangoproject.com/en/3.2/topics/templates/</a></li>
        <li><a href="https://docs.djangoproject.com/en/3.2/ref/templates/language/">https://docs.djangoproject.com/en/3.2/ref/templates/language/</a></li>
<ol/>
<ol/>
    <br>
    <ul>
       <li>Para el parser (Web scraping) he sacado la información de la página:</li>
    </ul>
    <ol>
        <li><a href="https://j2logo.com/python/web-scraping-con-python-guia-inicio-beautifulsoup/">https://j2logo.com/python/web-scraping-con-python-guia-inicio-beautifulsoup//</a></li>
        <li><a href="https://docs.djangoproject.com/en/3.2/ref/request-response/">https://docs.djangoproject.com/en/3.2/ref/request-response/</a></li>
    <ol/>
<ol/>
{% endblock %}
{%block lateral%}
<br>
    <p>Información sobre el proyecto</p>
        {% load static %}
        <img src="https://auteide.com//wp-content/uploads/2016/07/informacion-logo-300x189.png" alt="logo header" width=60% align="right" heigth="100">
        <br><br><br>
        <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo oscuro">
        </form>
        <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo claro">
        </form>
        <br>
    </strong>
{% endblock %}

final-LoVisto/ProyectoFinal/templates/lovisto/Recursomarca.html
{% extends 'lovisto/PaginaContenido.html' %}
{%block aportacion%}
<div class="marca">
    <p>{{title}}</p>
    <img src={{imagen}} width="300">
    <p>{{text}}</p>
    <p>© Julio 2021 Unidad Editorial Información Deportiva, S.L.U. Todos los derechos reservados.</p>
    <p><a href="{{content.url}}">Publicado en marca</a>
</div>
{%endblock%}

final-LoVisto/ProyectoFinal/templates/lovisto/Recursoreconocidoerror.html
{% extends 'lovisto/PaginaContenido.html' %}
{%block aportacion%}
  Información extendida no disponible
{%endblock%}

final-LoVisto/ProyectoFinal/templates/lovisto/Recursowikipedia.html
{% extends 'lovisto/PaginaContenido.html' %}
{%block aportacion%}
<div class="wikipedia">
  <p>Artıculo Wikipedia: {{title}}</p>
  <img src={{imagen}}>
  <p>El texto está disponible bajo la Licencia Creative Commons Atribución Compartir Igual 3.0; pueden aplicarse cláusulas adicionales. Al usar este sitio, usted acepta nuestros términos de uso y nuestra política de privacidad.
Wikipedia® es una marca registrada de la Fundación Wikimedia, Inc., una organización sin ánimo de lucro.
  <a href={{content.valor}}>Artículo
  original</a>.</p>
</div>
</div>
{%endblock%}

final-LoVisto/ProyectoFinal/templates/lovisto/aportaciones.html
{% extends 'lovisto/schema.html' %}
{%block cuerpo%}
    {%if content_list%}
<strong>
    <h1>
        En esta página encontraras
        <br>todas las aportaciones que hemos recibido.
        <br>Ordenadas de recientes a mas antiguas<br>
    </h1>
    <ul>
        {%for content in content_list%}
             <li><a href="{{content.url}}">{{content.title}}</a></li>
        {%endfor%}
    </ul>
    {%else%}
        <p>No hay contenidos que mostrar</p>
    {%endif%}
</strong>
{% endblock %}
{%block lateral%}
<p>
<p><strong>Aportaciones</strong></p>
    <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo oscuro">
        </form>
    <p><strong></strong></p>
        <form action="" method ="POST">
                {% csrf_token %}
            <input class="boton_personalizado"type="submit" name="action" value="Modo claro">
        </form>
    <br>
</p>
{%load static%}
    <img src="https://media1.tenor.com/images/045b70fb84a6d159a815c75daf00b3f4/tenor.gif?itemid=5078110" alt="logo header" width=30% align="left" heigth="100">
<br>
{% endblock %}